apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 1
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: mynode-app
        image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: RDS_HOSTNAME
          value: database-1.cmw3l0js7ara.ap-south-1.rds.amazonaws.com
        - name: RDS_USERNAME
          value: postgres
        - name: RDS_PASSWORD
          value: postgres
       