version: "3"
services:
  nodeapi:
    image: node:alpine
    environment:
      RDS_HOSTNAME: "database-1.cmw3l0js7ara.ap-south-1.rds.amazonaws.com"
      RDS_USERNAME: "postgres"
      RDS_PASSWORD: "postgres"
      RDS_PORT: "5432"
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    command: sh -c "cd /home/node/app && npm install && npm start "
    

